bootstrap:
  # 1 block before the actual bootstrap
  - slot: 10072043
    hash: 792cb81c3473e57c5b26324d45f26f936ad85e0a9949134a275f3cde7024ae67
deployment:
  # Always Fail
  - 51936f3c98a04b6609aa9b5c832ba1182cf43a58e534fcc05db09d69
  # V | Protocol Script
  - f91fd86ba6752fa09c00860a4e73a708b621150da24d0996dda5730a
scripts:
  mpTeiki: b3e06b950aa702ff03915df51a39a4f515cc303bb5c9a0813c568fd2
  nftTeikiPlant: 9fd46480023b171509222fd7d9ecc131b63f9a7b8b62cbae23770c7b
  nftProtocol: 33400b3f96591684f98be1bce8b769d95b03fd0e4ddec913bd258e71
  # For these fields, latest version goes first
  atProject:
    - f7bfee860142917082618d020964a0e723682004338aa5ace011d026
  mpProofOfBacking:
    - 8e0217ea2d3f175a58950539ca3bc891b41d521041cac1415d568c29
  vDedicatedTreasury:
    - b226097900bf7478d0df9e54a01615055824e5f8422e3d3da53aeaff
  vSharedTreasury:
    - ef0eca97c65f8ae120b604604bc013744be2d7beb4aaf44e906539e5
  vOpenTreasury:
    - 24e3992ab2ec573c4a5b90b6143e49e107ff95743c96fe61fb694d33
